# Generated by Django 2.2.13 on 2020-06-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
